### ISSUE TITLE
23.04.2024 Meetup debrief

### ISSUE THREAD

**Issue by hola-asya** [tech-connect-meetups/tech_vlc#11]
## Количество участников

Цель: 51
Факт: 43

## Помещение 
Wayco Ruzafa, зал Crisol
Терраса хорошо отработала во время нетворкинга, в зале никто не стоял, оказалось тесновато

Показывали как дойти, 80% не были в коворкинге, узнавали, как снять место и поработать оттуда

! написать, что это имя мы напечатаем на бейджике, напишите его нормально

дата - был большой квиз, некоторые люди не пришли — нужно координировать с календарем больших мероприятий

**Техническое обеспечение**
- телевизор 65, нормально
- на некоторых 
- микрофон не понадобился
- проверили все куары даже с задних рядов
- музыка ок - использовали колонку + шнур

**Еда и напитки**
- заказали на 30 чел, осталось много закусок, воды, колы (30 бут воды, по 5-10 софт дринкс - кола, кола зеро, чай, фанта, мин вода с газом)
- очень высокая цена - 10 евро на чел

## Коммуникация и логистика (регистрация, координация, вход):
- нужна [автоматизация регистрации ](https://github.com/tech-connect-meetups/tech_vlc/issues/9)
- 2 чел хватило, чтобы раздавали бейджики с напечатанными именами - фидбек "прикольно, что заморочились", пытались забрать все наклейки (нужно разрезать)
Идея не делать надписи guest и crew, потому что никакой смысловой нагрузки нет, лучше просто у организаторов делать с лого
Еще идея, написать хобби или интерес, по которому люди могли бы объединяться
Не везде прогрузилась до конца фамилия - проверить табличку страйпа (Сергей М. и Мостовой)
- если идем в бар, надо договариваться с баром на промокод и говорить его людям (или ставить на слайд)

### Эффективность каналов коммуникации

**До:**
- анонс в Тех канале
- анонс с Vaaamos - неправильно указали время начала (19:00)
- рассылка подтверждения вручную в тг - 2 чел не увидели

**Во время:** 
- фотографа не упомянула в списке волонтеров
- 23 заполнили ментиметер
- нужно закладывать 5-10 мин на досбор людей: указывать начало в 18:50, по факту начинать в 19

**После:**
- пост-коммуникация через 3-4 дня 

**Координация организаторов во время мероприятия**
- когда даем ТЗ фотографу, сразу просить когда нужны фотки
- на следующий раз можно взять рации

## Вовлеченность

**Вовлеченность в презентации и темы:** 
- хорошая вовлеченность, времени очень мало и на доклады, и на вопросы
- 20 мин на доклады это очень мало, надо мин 45 мин на доклад (час с вопросами)

**Подготовка спикеров:** 
хорошая, нужно слушать перед презентацию - нужно обговаривать на старте про прогон: нужен более осмысленный подход и анонсировать лучше, о чем доклад (например, собирать тезисы вместо просто темы доклада)

**Ожидания/реальность и фидбек от участников:**
- темы очень общие, не совсем то, что люди ждали
- хотелось про адаптацию, про налоги, про софты — что-то более прикладное 
- некоторые хотят выйти с темой, но им нужна помощь, какая тема больше зайдет — можно на открытый микрофон приглашать таких людей
- сформировать elevator speach и записать его в виде кружочка в канале
- нужна концепция как собирать доклады

## Итог

**Внезапные проблемы**
-  неотсмотренные доклады
- неожиданность с таймингом - люди пришли к 19
- непонятки с баром со скидкой, пообещали 10% скидку, не всем дали
- непонятно, что делать с людьми, которые пришли на месте

**Самые крутые штуки**
- волонтеры
- площадка производила впечатление
- 30+ пошли в бар и сидели там полночи "самый крутой нетворкинг"!

**Самые провальные штуки**
- неправильно указали время начала в Vaaamos
- время докладов и вопросов
- открытый микрофон — зачем это надо?

 ## Что дальше

- [x] анонс ретро и фоток
- [x] анонс следующего митапа в Турии

**Comment by GoSvetlanada** [comment]
Ну че вы, ну. Наговариваете на Вамос) https://t.me/Vaaaamos/546. Написано жеж, в 18:40. Видимо не надо указывать, что первый доклад в 19.
