### ISSUE TITLE
 IT Picnic May'31 Retro 

### ISSUE THREAD

**Issue by hola-asya** [tech-connect-meetups/tech_vlc#13]
## Количество участников

Цель: 50
Факт: 42

## Помещение 

**Техническое обеспечение**
- колонка с музыкой — это хорошо, достаточно удобное расположение
- телефон сел к концу
- саморегистрация хорошая прописанная по шагам, можно распечатать еще 
- не продумали зон для мусора
- туалет оказался рядом случайно, но это надо продумывать 

**Еда и напитки**
- [кейтеринг](https://www.instagram.com/vikey_catering?igsh=MTVyb2c4MDRlMHliaw==) огонь, очень удобно и хорошо, заказали на 50 чел. Первыми ушли фрукты, сэндвичи доели под конец. Остался попкорн и чипсики. Сладостей осталось много.
- люди не поняли, что напитки нужно нести с собой — лучше сделать список, что взять и принести с собой или делать софт дринки тоже (кола, чай)
- воды было норм - 60 бутылок, из них осталось порядка 15 - нужно подписывать
- можно мясные чипсы

## Коммуникация и логистика (регистрация, координация, вход):

**Встреча гостей**
- на регистрации отлично отработали наклейки, но людям не хватило наклеек-настроений. хорошо сработало на интерактив.
- не хватило организованной активности (типа игры или что-то такое, можно было взять мячи)
- было бы прикольно сделать какой-то интро или карточки с вопросами
- хорошо, когда есть социальный агент
- пледы зашли, когда люди устали

### Эффективность каналов коммуникации

**До:**
- люди не поняли, что надо приносить свои напитки и подстилки
- не все поняли, что можно задонатить больше 10 евро

**Во время:** 
- инструкция норм отработала, но можно было сделать заранее и прописать туда побольше
- нужно говорить, что оно ограничено по времени и что мы хотим, чтобы люди сделали (предупредить, что нужно убрать мусор и все такое)
- наклейки не полетели, потому что не было агентов
- не залетели зоны, потому что надо было делать в них движухи

**После:**
- быстро отдали фотки и коммуникацию, ура!

**Координация организаторов во время мероприятия**
- хорошо менялись на встречу и регистрацию участников
- по отдельности разговорили некоторых людей

## Вовлеченность
Подготовка спикеров: нам нужно готовить первую речь (для чего собрались, почему мы не токсичные и чего мы будем делать)
Ожидания/реальность и фидбек от участников:
- satisfaction rate 88%

## Итог

**Внезапные проблемы**
- туалет закрылся
- не скоординировали завершение пикника

**Самые крутые штуки**
- [фотограф](https://www.instagram.com/andrei.andriukhov?igsh=cnh6Y3Zmb2p2cHQw)!
- [кейтеринг](https://www.instagram.com/vikey_catering?igsh=MTVyb2c4MDRlMHliaw==)

**Самые провальные штуки**
- зоны вообще не зашли, возможно зашли бы с активностями
- слишком рано начали, можно начинать в 18:30, с пиковой активностью в 19

**Идеи**
- фотозоны с брендированием
- игры формата тим-билдинга
- спортивные игры
- сделать пешеходный квест
- можно сделать 2-3 зоны с активностями
- раскидать рандомные куар коды с л[инктри сообщества](https://github.com/tech-connect-meetups/tech_vlc/issues/12)

 ## Что дальше
- [x] следующий ивент - мб в фаталисте
- [ ]

**Comment by Itbfb** [comment]
Првоести полноценное ретро и выложить в доступ, это круто, очень

**Comment by hola-asya** [comment]
> Првоести полноценное ретро и выложить в доступ, это круто, очень

На том и стоим!)
Спасибо

Кстати, забыла закрыть issue, заодно и завершу этот цикл 🏋️‍♂️

**Comment by hola-asya** [comment]
<img width="450" alt="Screenshot 2024-11-06 at 10 35 16" src="https://github.com/user-attachments/assets/cba48a06-cbd7-4c22-81da-d2b028665e2d">
