### ISSUE TITLE
Крыша Пати 10-07-24 Кик офф

### ISSUE THREAD

**Issue by GoSvetlanada** [tech-connect-meetups/tech_vlc#14]
**Идеи**
- сделать костяк спикеров чтобы мы понимали что 10-15 выступлений будет (больше технических тем), возможно сделать 2 раунда в сетке
- сделать ретро зону со стикерами: фидбек сетка
- если это итоговое мероприятие, нужен итог, торит, ленточку -- час диджея в конце
- идея сделать зону танцев отдельно
- помещение: время работы (с 19 до 22 в идеале), уборка включена, вместимость 100 чел, есть куда клеить бумажки, музыка, красивое место, пространство лучше должно быть единым, фуршет
- сначала обсудить темы со спикерами, затем сделать коммуникацию, что можно будет гибко занять слот, обсудить свой вопрос и поговорить с умными чуваками за жизнь и работу
- обсудить со спикерами их темы докладов и формат (примерно 10 человек), чтобы знать, что у нас будет контент + 10 свободных слотов
- медалька для тех, кто был на всех ивентах
- сделать фотозону 

**Тайминг:**
18:30 сбор
19:00 - 19:15 вступительная речь, ой какие мы классные и презентация формата
19:15 - 19:25 записываем темы
19:25 - 20:00 питчинг
20:00 - 20:40 1 раунд
20:45 - 21:25 2 раунд 
21:25 - 22:00 тортик 

**Реквизит:**
- бумага для флипчартов
- хорошие толстые маркеры
- стикеры
- жвачка или скотч

**Требования к помещению**
— красивая, желательно фенси вида, руфтоп — идеально
— вместимость 100-120 человек 
— нужны стены, чтобы можно было приклеить на них листы флипчарта
— помещение должно быть большим, чтобы люди могли в разных сторонах разделиться на 5-6 групп по 15 человек
— нужны какие-то стулья/диванчики, но можно не на все 120 человек, просто чтобы отдохнуть 
— место для фуршета (то есть столы) 
— большие колонки, чтобы включить музыку или поставить диджея
— уборка включена 
— время с 19 до 23

**Варианты помещений:**
- Руфтоп Вайко Русафа - ждем цены, работают до 21:00 - Света
- Фабрика де Йело - внутри влезет 100 чел, возможно можно будет сделать вечеринку ок 600 евро - Света
- Меркат стеклянный - Яна
- gulagroup - Ася
- узнать у Оли и Алены по поводу площадок - Яра
- узнать у флайин бин про аренду - Яна

Первый чек: среда, 20 июня
Второй чек и финализация: пятница, 21 июня

Таня делает голосовалку за следующую волонтерскую встречу, чтобы согласовать детали и распределить работу

**Comment by GoSvetlanada** [comment]
Помещение: [WayCo Miramar Terrace ](https://wayco.es/en/salas/miramar-terrace/ ) — запросили счет на оплату 26 июня, попросили доп.час, сейчас с 18 до 21. 

**Сценарий:** 

1. Люди пришли в Вайко, их встретили внизу, рассказали что где, отправили на лифт 
2. На 5 этаже пришли, увидели инструкцию, там же выдали бейдж, показали куда идти, где туалеты. Показываем куда идти
3. В этот момент уже есть напитки в зоне кейтеринга и распределено 5 зон со столами где стоят спикеры
4. Люди пришли в зону 1 (внутри), там телек, на нем презентация сообщества 
5. Начало мероприятия: Света и Ася рассказывают про сообщество, рассказывают про формат, призывают участвовать
6. Ретро сообщества: фидбек сетка (сказать, что можно пойти и оставить отзыв)
7. 10 минут на подготовку темы
8. 30 минут на то, чтобы люди придумали тему + запитчили ее. Во время питчинга Никита записывает в Миро темы. 
9. Спикеры и мы распределяемся за столы
10. Второй круг спикеров 
11. Ретро сообщества: фидбек сетка (напомнить)
12. Финальная речь про ивент. Торт со свечками, нетворкинг, чай/кофе 
13. Подарить медальку тем, кто был на всех ивентах 
14. Рассказать куда можно пойти после мероприятия 

**Зоны:** 

- Встреча людей на ресепшен 1 этажа — нужен человек, табличка о том, что тут митап + список участников и бейджи — отправляем людей на 5 этаж
- Нужен указатель «Что тебе нужно сделать» — напечатанный лист — прописать инструкцию — **Таня** 
- На 5 этаже у лифта выдаем бейджики (нужен стол) — **4-5 человек**  
- QR-код, где описано что где (**Виталя и Никита**) — развесить везде по площадке и распечатать — лендос, где будет написано про формат, логотип, ссылки на все ресурсы сообщества — **5 июля**
- Сделать сетку для докладов, чтобы Никита сделал миро (**Ася и Никита**)
- Презентация сообщества + рассказываем про формат анконференс (**Ася и Света**) — сделать презентацию + объяснить про то, как эти пользоваться — сетка мероприятия 
- Зоны выступления спикеров (5 столов с номерочками) 
- Зона общения с докладчиком после выступления

**Что сделать:** 
- есть ли звук на террасе, для интро нужен микрофон (Света) 
- можно ли на экран входа поставить нашу заставку (Света) 
- кейтеринг: нужен кофе и чай к торту 
- можно ли поставить стол внизу, чтобы регистрировать людей (или куда можно) (Света) 
- сделать фотозону — нужно продумать (Яна?) 
- подготовить столы для спикеров
- сделать треугольнички на столы с цифрами (зоны анконференса) — распечатать — **Мила** 
- листки с QR-кодами **Мила** 
- распечатать бейджики **Таня и Виталя** 
- распечатать табличку о том, что тут митап **Мила* 
- QR-код, где описано что где (**Виталя, Таня и Никита (верстает)**)
- инструкция на 5 этаже **Мила** 
- договориться с фотографом **Ася**
- в анонсе нужно сразу написать где что будет, чтобы люди, которые опоздали пришли куда надо **Света**
- 10-15 подготовленных спикера с возможностью одновременно проводить 6-7 треков (**Мила, Настя, Яра** общаются с людьми, чтобы отобрать темы)
- найти тортодела и заказать торт на 100 человек **Света** 
- распечатать карточки игры «Стать ближе» **Виталя и Таня** 
- купить медальки (сначала посчитать сколько)


Купить: 
- тарелки для торта 
- мусорные пакеты 
- ложки для торта 
- свечки для торта 
- бейджики 
- маркеты 
- торт
- стикеры для ретро (фидбека)
- медальки шоколадные

**Comment by hola-asya** [comment]
новая предварительная дата ивента 
11 октября
