### ISSUE TITLE
April Tech VLC - kick-off

### ISSUE THREAD

**Issue by hola-asya** [tech-connect-meetups/tech_vlc#6]
**Дата: 23 апреля
Локация:  Wayco Ruzafa,  Sala Criso**

**Митап**

Ася
1. Спросить у менеджера про вместимость зала: 50 + 25 мест, или 50/25 + Как попасть в зал, есть ли таблички?
2. Получить прайс на закуски, просчитать, хватит ли
3. Сходить в коворкинг, посмотреть зал, спросить по технический гэп для прогона (+Виталий для тех поддержки)
4. Нужен бот обратной связи !  - Виталий
5. Голосование делаем в общем чате по темам докладов на предстоящий митап! - Света
6. Покупаем ли подписку ментиметр? - Ася и Света

**_Зоны_**: 

Встреча гостей/приветствие 
1. Встречать людей на входе, проверять по спискам - Таня и Катя
3. Вода, закуски -  Ася
4. Купить стикеры для бейджиков и маркеры -  Таня и Виталий
5. Печатаем ли имена? Таня и Виталя
7. В начале объявить план и тайминг! - Ася
8. Опрос в начале, Давайте познакомимся - Ася и Света 
    1. Как долго ты в Валенсии?
    2. Твоя специализация: Разработка, Архитектура, Дизайн, Продакт…
    3. Твой грейд: Джуниор, Мидл, Синьор, Лид, Лид+
    4. Чего ждешь от мероприятия? 

Доклады
1. Кто включает презы? - Ася или Катя
2. Модератор для вопросов - сам докладчик
3. Связаться с докладчиками, обсудить репетицию и разогрев перед выступлениями (за 30 минут) - Катя
4. Узнать, нужен ли комп?  - Ася

Музыка
1. Узнать, есть ли микшер - Ася 
2. Нужен человек, кто будет включать звук - Виталий
3.  Сделать подборку музыки для фона - Катя

Дизайн - Катя М, Ася координирует
1. Общий брендинг
2. Шаблон презентации
3. Заставка на экран

Открытый микрофон - Ася
1. Объявление
2. Привести примеры, с чем можно выйти с микрофоном 
3. Ограничение штаны и 5 минут

Нетворкинг - свободный

Бот
Обратная связь, темы докладов и все такое -Виталий
Форма обратной связи после митапа участникам - идея: ачивки за обратную связь по мероприятию и посещение митапов, если ходишь на все митапы, получаешь именной бейдж — дают стикер на бейдж если даешь обратную связь, посетил 10 митапов — получаешь стикер

**Comment by hola-asya** [comment]
Следующие шаги
- просмотр коворинга - Ася и все остальные
- координация докладчиков - Катя
- бот - Виталий

**Comment by vitalynec** [comment]
Бот добавлен, можно поиграть перед запуском на массы

**Comment by hola-asya** [comment]
-  просмотр согласован
 - прийти на тех.подготовку зала можно будет с 16.30

**Comment by hola-asya** [comment]
Вопросы, которые осталось решить:

- [ ] ревью бота и его анонс - механизм голосования за доклады в чате
- [ ] анонс чатика с вакансиями
- [ ] подписка ментиметер или альтернативы
- [ ] опрос в начале
- [ ] заказать фуршет
